// Check that the exception type check works.

exception truth {};

int main(int argc, char * argv[]) {
	try {} catch (int e) {}
	try {} catch (truth & e) {}
	try {} catchResume (int e) {}
	try {} catchResume (truth & e) {}
}
